spring:
  datasource:
    name: test
    url: "jdbc:mysql://yisquarecs.sedns.cn:3366/dbhap?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true"
    username: root
    password: yisquare2016
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  profiles:
    active: dev

mybatis:
  mapper-locations: mapper/web/*.xml
  type-aliases-package: com.yisquare.wifi.probedataimporttool.web.entity